apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.storage.classname }}
  storageClassName: {{ .Values.storage.classname | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.access | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" | quote}}
