apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  ports:
   - port: 5432
  selector:
   app: {{ .Release.Name }}-postgres
