apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-provider
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "provider8030"
      port: 8030
      targetPort: 8030
  selector:
    app: {{ .Release.Name }}-provider
