apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-operator-api
  name: {{ .Release.Name }}-operator-api
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount | default 1 }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator-api
    spec:
      containers:
      - name: {{ .Release.Name }}-operator-api
        image: {{ .Values.image.repository | default "oceanprotocol/operator-service" }}:{{ .Values.image.tag | default "v4main" }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ end }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" | quote }}
        env:
        - name: requests_cpu
          value: "2"
        - name: requests_memory
          value: "4Gi"
        - name: limits_cpu
          value: "4"
        - name: limits_memory
          value: "16Gi"
        - name: ALGO_POD_TIMEOUT
          value: "3600"
        - name: SIGNATURE_REQUIRED
          value: "0"
        - name: ALLOWED_PROVIDERS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-networks
              key: publicProviders
        - name: OPERATOR_ADDRESS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-networks
              key: publicOperator
        - name: DEFAULT_NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: ALLOWED_ADMINS
          value: '["postgresadmin"]'
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres
              key: POSTGRES_PORT
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

