apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-operator-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-operator-api
  ports:
    - name: "operator-api8050"
      port: 8050
      targetPort: 8050
